### ISSUE TITLE
Can you please update for Swift 4.2???

### ISSUE THREAD

**Issue by sdevo619** [BalestraPatrick/WhatsNew#29]
Seeing this error message as of Xcode 10 and Swift 4.2. Can you please update as soon as possible? Thank you very much!!!!

![screen shot 2018-10-02 at 1 11 19 pm](https://user-images.githubusercontent.com/7008354/46374158-db0df180-c644-11e8-9b77-7c624e9da113.png)

**Comment by BalestraPatrick** [comment]
Are you using the right version? I've pushed an update for Swift 4.2 and Xcode 10 about 2 weeks ago. please run `pod update` or whatever dependency manager you're using and let me know.

**Comment by sdevo619** [comment]
Yes, I am pulling it down using Cocoa Pods, and have already updated all my pods today.

pod 'WhatsNew'

**Comment by BalestraPatrick** [comment]
Can you please run `pod repo update` and try again with a `pod update`? If that doesn't work, try specifying the version manually and see what it says.

**Comment by sdevo619** [comment]
Version is WhatsNew (0.4.4). Still having the same issue. Your code needs to be updated according to this.


![screen shot 2018-10-02 at 1 48 28 pm](https://user-images.githubusercontent.com/7008354/46376077-eca5c800-c649-11e8-843b-e56e8efadd5b.png)

**Comment by BalestraPatrick** [comment]
Running my project in Xcode 10 and Swift 4.2 doesn't show that issue. Can you please try to download and run the example project in this repo and let me know if you can reproduce it?

**Comment by sdevo619** [comment]
Sorry for wasting your time on this, and thank you very much for the super fast response!!! I figured out what the issue was. I had not updated the main project file code using the builtin tool of this particular project, and once I did, the error I was seeing went away. This has been a particularly rocky transition, as Apple broke a lot when they release Xcode 10, so again, sorry about that. Keep up the great work!!! Thank you!!!
